#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: postgres
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: postgres
#  template:
#    metadata:
#      labels:
#        app: postgres
#    spec:
#      containers:
#        - name: postgres
#          image: postgres:14
#          env:
#            - name: POSTGRES_DB
#              value: ordersdb
#            - name: POSTGRES_USER
#              value: postgres
#            - name: POSTGRES_PASSWORD
#              value: gera1234
#          ports:
#            - containerPort: 5432
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres-service
#spec:
#  ports:
#    - port: 5432
#  selector:
#    app: postgres
