version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: order-db
    environment:
      POSTGRES_USER: order-sub
      POSTGRES_PASSWORD: new
      POSTGRES_DB: order-sub
    ports:
      - "5435:5432"
    networks:
      - shared-network

  app:
    build: .
    container_name: order-service
    depends_on:
      - db
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/order-sub
      SPRING_DATASOURCE_USERNAME: order-sub
      SPRING_DATASOURCE_PASSWORD: new
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_AMQP_DESERIALIZATION_TRUST_ALL: "true"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
