# docker-compose.yml
services:
  db:
    image: postgres:latest
    container_name: order-db
    environment:
      POSTGRES_USER: order-sub
      POSTGRES_PASSWORD: new
      POSTGRES_DB: order-sub
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: order-service
    depends_on:
      - db
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/order-sub
      SPRING_DATASOURCE_USERNAME: order-sub
      SPRING_DATASOURCE_PASSWORD: new

