apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: andreww827/api-gateway:latest
          ports:
            - containerPort: 8080
          env:

            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_MAIN_WEB_APPLICATION_TYPE
              value: reactive

            # User service route
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: user-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: http://user-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: Path=/users/**

            # ProductCart service route
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: productcart-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: http://productcart-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: Path=/carts/**,/products/**

            # Payment service route
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
              value: payment-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
              value: http://payment-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
              value: Path=/payments/**,/refunds/**

            # Order service route
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_ID
              value: order-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_URI
              value: http://order-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
              value: Path=/orders/**
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
