# docker-compose.yml
services:
  db:
    image: postgres:latest
    container_name: paymentgp-db
    environment:
      POSTGRES_USER: payments-sub
      POSTGRES_PASSWORD: new
      POSTGRES_DB: payments-sub
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: paymentgp-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/payments-sub
      SPRING_DATASOURCE_USERNAME: payments-sub
      SPRING_DATASOURCE_PASSWORD: new
