version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: payment-db
    environment:
      POSTGRES_USER: payments-sub
      POSTGRES_PASSWORD: new
      POSTGRES_DB: payments-sub
    ports:
      - "5434:5432"
    networks:
      - shared-network

  app:
    build: .
    container_name: payment-service
    depends_on:
      - db
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/payments-sub
      SPRING_DATASOURCE_USERNAME: payments-sub
      SPRING_DATASOURCE_PASSWORD: new
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - shared-network

networks:
  shared-network:
    external: true
