spring:
  datasource:
    url: jdbc:postgresql://db:5432/payments-sub
    username: payments-sub
    password: new
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  application:
    name: payment-service
  main:
    web-application-type: reactive
