spring:
  application:
    name: payment-service
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/payments-sub
    username: payments-sub
    password: new
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
