spring:
  datasource:
    url: jdbc:postgresql://db:5432/order-sub
    username: order-sub
    password: new
  amqp:
    deserialization:
      trust:
        all: true
  application:
    name: order-service
  main:
    web-application-type: reactive
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
