spring:
  amqp:
    deserialization:
      trust:
        all: true
  application:
    name: order-service
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/order-sub
    username: order-sub
    password: new
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
