server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: productcart-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    mongodb:
#      uri: mongodb://root:example@mongo:27017/?authSource=admin
      uri: mongodb://root:example@localhost:27017/?authSource=admin
      database: productcart
    redis:
      host: redis_cache
      port: 6379
  cache:
    type: redis

# Custom properties should be at the root level, not nested under spring
payment:
  service:
    url: http://payment-service:8080

instance_name: "Main Instance"

feign:
  httpclient:
    enabled: true